openapi: 3.0.3
info:
  title: nhApiod-proxy API
  description: |
    A high-performance proxy service for nhentai with PDF generation capabilities and CDN support.

    ## Features
    - High-performance gallery data fetching
    - Automatic PDF generation with background processing
    - Intelligent caching system
    - Optional R2 storage integration for CDN delivery
  version: 1.0.0
  contact:
    name: GitHub Repository
    url: https://github.com/yourusername/nhApiod-proxy

servers:
  - url: http://localhost:5001
    description: Local development server

paths:
  /health-check:
    get:
      summary: Check service health
      description: Returns the health status of the service and its components
      operationId: healthCheck
      tags:
        - System
      responses:
        "200":
          description: Service health status
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthCheckResponse"
        "500":
          description: Service health check failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /get:
    get:
      summary: Get gallery data
      description: Fetches gallery data and optionally triggers PDF generation
      operationId: getGallery
      tags:
        - Gallery
      parameters:
        - name: id
          in: query
          description: Gallery ID
          required: true
          schema:
            type: integer
            format: int64
        - name: check_status
          in: query
          description: Only check PDF processing status
          required: false
          schema:
            type: boolean
            default: false
      responses:
        "200":
          description: Gallery data retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GalleryResponse"
        "400":
          description: Invalid gallery ID
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Gallery not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /pdf-status/{gallery_id}:
    get:
      summary: Check PDF processing status
      description: Returns the current status of PDF generation for a gallery
      operationId: getPdfStatus
      tags:
        - PDF
      parameters:
        - name: gallery_id
          in: path
          description: Gallery ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: PDF status retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PDFStatusResponse"
        "404":
          description: Gallery not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    HealthCheckResponse:
      type: object
      required:
        - status
        - service
        - timestamp
        - cookies_ok
      properties:
        status:
          type: boolean
          description: Overall status of the response
        service:
          type: string
          description: Service name
        timestamp:
          type: number
          format: float
          description: Current timestamp
        cookies_ok:
          type: boolean
          description: Cookie manager status

    GalleryResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: boolean
          description: Success status of the request
        data:
          type: object
          description: Gallery data
          properties:
            id:
              type: integer
              description: Gallery ID
            media_id:
              type: string
              description: Media ID
            images:
              type: object
              properties:
                cover:
                  $ref: "#/components/schemas/ImageInfo"
                pages:
                  type: array
                  items:
                    $ref: "#/components/schemas/ImageInfo"
            pdf_status:
              type: string
              enum: [unavailable, processing, completed, error]
              description: PDF generation status
            pdf_url:
              type: string
              description: URL to the generated PDF (if available)

    PDFStatusResponse:
      type: object
      required:
        - status
        - pdf_status
      properties:
        status:
          type: boolean
          description: Success status of the request
        pdf_status:
          type: string
          enum: [not_started, processing, completed, error]
          description: Current PDF processing status
        pdf_url:
          type: string
          description: URL to the generated PDF (if completed)
        error:
          type: string
          description: Error message (if status is error)

    ImageInfo:
      type: object
      properties:
        url:
          type: string
          description: Original image URL
        cdn_url:
          type: string
          description: CDN URL (if R2 storage is configured)
        thumbnail:
          type: string
          description: Thumbnail URL
        thumbnail_cdn:
          type: string
          description: CDN thumbnail URL (if R2 storage is configured)

    ErrorResponse:
      type: object
      required:
        - status
        - reason
      properties:
        status:
          type: boolean
          description: Always false for error responses
        reason:
          type: string
          description: Error message

tags:
  - name: System
    description: System-related operations
  - name: Gallery
    description: Gallery data operations
  - name: PDF
    description: PDF generation operations
