services:
  - type: web
    name: nhApiod-proxy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wbs-apiod:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    autoDeploy: true 